### ISSUE TITLE
RetentionPeriodReason validation

### ISSUE THREAD

**Issue by tittarii** [City-of-Helsinki/helerm-ui#127]
Need to "hard code" validation that if RetentionPeriod === '-1' then RetentionPeriodReason should be empty. This is of warn type validation message.

**Comment by Ta1Nur** [comment]
No need to "hard code" - it works now and only issue what UI do not reqocnize is this combination.

RetentionPeriod is "-1" and RetentionPeriodStart should be empty, if there is value in RetentionPeriodStart attribute, Validation should inform it as ERROR and users needs to correct it. API do not allow this and informs it in API response text
![image](https://user-images.githubusercontent.com/14962739/34388600-429878ae-eb3d-11e7-9338-7f4782971da9.png)
