### ISSUE TITLE
Minor Fix - Record labels layout

### ISSUE THREAD

**Issue by Ta1Nur** [City-of-Helsinki/helerm-ui#147]
Minor - did appear in ios tablet, both Safari & Chrome

Record labels UI component hide i.e. dropdown and this may affect also to sticky header vieving partially (discussed in demo)

View picture
![image](https://user-images.githubusercontent.com/14962739/34410272-a9c84726-ebd7-11e7-917a-84f2c2d03f76.png)

**Comment by vaaralav** [comment]
Couldn't recreate the issue with simulated iPad Air 2 running iOS 11.2 and Safari 11.0. Maybe it's something that the simulator doesn't do but the real thing does.

**Comment by Ta1Nur** [comment]
Ok, we can leave this for now and it is just for information and perhaps will help later. I will close this issue.
