### ISSUE TITLE
Navigation menu search resets when search input is focused after blur

### ISSUE THREAD

**Issue by vaaralav** [City-of-Helsinki/helerm-ui#170]
![helerm-ui-navigation-search-input-issue](https://user-images.githubusercontent.com/8571541/34609573-0ae22488-f226-11e7-8f0c-c43308844bba.gif)

**Comment by vaaralav** [comment]
The problem is most likely this `onClick` handler on line 6: https://github.com/City-of-Helsinki/helerm-ui/blob/0a294e932d7eb856bcfffff5f2a44e65036a8d29/src/components/InfinityMenu/searchInput.js#L4-L9

**Comment by vaaralav** [comment]
The problem is most likely the `onClick` handler on line 6: https://github.com/City-of-Helsinki/helerm-ui/blob/0a294e932d7eb856bcfffff5f2a44e65036a8d29/src/components/InfinityMenu/searchInput.js#L4-L9

**Comment by Ta1Nur** [comment]
Tested and fix works.
