### ISSUE TITLE
TOS print view to show classification data

### ISSUE THREAD

**Issue by tittarii** [City-of-Helsinki/helerm-ui#190]
Add classification data (description, description_internal, related_classification, additional_information) to TOS print view
Remove print button from classification view
Print view to support printing to excel, so that label and values are pairs

**Comment by Ta1Nur** [comment]
Reopen this new layout and header name

![image](https://user-images.githubusercontent.com/14962739/36535287-d290c6a8-17d1-11e8-9ab8-90703f816e52.png)
