### ISSUE TITLE
InformationSystem field should be visible

### ISSUE THREAD

**Issue by tittarii** [City-of-Helsinki/helerm-ui#191]
InformationSystem field should be visible even it is not required

**Comment by Ta1Nur** [comment]
Issues in Phase and in Action when Add new and give not listed value i.e. in dev environment "Other system" press enter, closes form -> adds new empty phase to end of current function or new empty action to end of current phase

**Comment by Ta1Nur** [comment]
User testin information in Finnish https://tree.taiga.io/project/juyrjola-tiedonohjausjarjestelma/issue/326
