### ISSUE TITLE
Add Phase Add Action bug in InformationSystem field [object Object]

### ISSUE THREAD

**Issue by Ta1Nur** [City-of-Helsinki/helerm-ui#230]
What happens
1. Add Phase or Add Action
2. Fill other fields OK
3. Activate InformationSystem (Tietojärjestelmä) field with mouse
4. Hit keyboard
5. [object Object] 
![image](https://user-images.githubusercontent.com/14962739/43002504-ace67ce8-8c31-11e8-8e7d-c92077c7f447.png)

6. If save function and try to edit it, do not work.

For your information - Add Record works fine.

Issue adds this code to attribute
"InformationSystem":{"isDefaultPrevented":null,"timeStamp":null,"isPropagationStopped":null,"defaultPrevented":null,"_dispatchInstances":null,"target":null,"eventPhase":null,"_dispatchListeners":null,"dispatchConfig":null,"_targetInst":null,"bubbles":null,"cancelable":null,"currentTarget":null,"isTrusted":null,"type":null,"nativeEvent":null}

**Comment by Ta1Nur** [comment]
Not ready issue in phase level still on tested in dev environment.
![image](https://user-images.githubusercontent.com/14962739/45281724-59152780-b4e1-11e8-8d53-f0373e59b271.png)

**Comment by villeristi** [comment]
This is because dev-version (`cd431b44aba0de183da3825eb66436afec1e5b18 `) is not anywhere near the most recent. @vikoivun could you check.

**Comment by Ta1Nur** [comment]
Works correctly with out [object Object] bug in both phase and action. I close this issue.
