### ISSUE TITLE
Make build work when without git checkout

### ISSUE THREAD

**Issue by vikoivun** [City-of-Helsinki/helerm-ui#87]
Currently the build fails if not working within a git checkout. This is due to GitRevisionPlugin, which is used to fetch the commit hash which is then shown in UI. Do the right JS-thing to handle the error thrown thereof.

**Comment by Ta1Nur** [comment]
@vikoivun this issue is still valid and should I get it sorted GitRevisionPlugin alternative needed if I get it right?
