### ISSUE TITLE
Select component in draft phase needs to handle both text and list values

### ISSUE THREAD

**Issue by Ta1Nur** [City-of-Helsinki/helerm-ui#98]
Beta development tried to solve issues when content is not yet finalized and values do not match value lists.  When browsing content not list values show, but when user tries to edit content in edit view, if value is not listed component do not show it. Also that user may type in not listed values text when function is draft. NOTE those draft values will not update attribute list values.

Something like this http://jedwatson.github.io/react-select/
![image](https://user-images.githubusercontent.com/14962739/32145608-2d704ca0-bcd4-11e7-8990-8d65683a5246.png)

Attributes mainly single value and also multivalued option is ready in API and not yet implemented in UI, first multivalued attribute is Tietojärjestelmä (InformationSystem). In that field we have now only text content. This enhancement needs discussing with API developer and product owner.

System has basic idea in draft phase content rules will not yet apply.
User can do validation in draft phase and then user knows what needs to be checked.
When function content is ready, user choose "Lähetä tarkastettavaksi" (send for review) and then all rules will apply - rule based validation to help review work.

**Comment by tittarii** [comment]
Fixed in PR #107
